version: '3'
services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.7
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "81:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8081:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    container_name: web-flask
    build: .
    ports:
      - "8080:5000"
    networks:
      - private flask
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql/mysql-server
    environment:
      - MYSQL_ROOT_PASSWORD=P4SSw0rd0!
    volumes:
      - dump-sql:/var/lib/mysql
    networks:
      - private flask
    ports:
      - "8807:3306"
    restart: always

networks:
  private flask:

volumes:
  dump-sql: